# Generated by Django 3.2.4 on 2021-08-18 16:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.IntegerField(default=0, verbose_name='Широта')),
                ('lng', models.IntegerField(default=0, verbose_name='Долгота')),
                ('fullness', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Заполненость')),
                ('capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Вместимость')),
            ],
            options={
                'verbose_name': 'Точка сбора мусора',
                'verbose_name_plural': 'Точки сбора мусора',
            },
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.IntegerField(default=0, verbose_name='Широта')),
                ('lng', models.IntegerField(default=0, verbose_name='Долгота')),
                ('registrationMark', models.CharField(max_length=10, verbose_name='Номерной знак')),
                ('points', models.ManyToManyField(to='cleaning.Point', verbose_name='Обслуживаемые точки')),
            ],
            options={
                'verbose_name': 'Мусоровоз',
                'verbose_name_plural': 'Мусоровозы',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('truck', models.ManyToManyField(to='cleaning.Truck', verbose_name='Обслуживаемые мусоровозы')),
            ],
            options={
                'verbose_name': 'Рабочий',
                'verbose_name_plural': 'Рабочие',
            },
        ),
    ]
