# Generated by Django 3.2.4 on 2021-08-20 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='truck',
        ),
        migrations.AddField(
            model_name='worker',
            name='truck',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cleaning.truck', verbose_name='Обслуживаемые мусоровозы'),
        ),
    ]
