# Generated by Django 3.2.4 on 2021-08-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0002_auto_20210820_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='lat',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=10, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='point',
            name='lng',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=10, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='lat',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=10, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='lng',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=10, verbose_name='Долгота'),
        ),
    ]
