# Generated by Django 3.2.4 on 2021-08-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0003_auto_20210820_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
